import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tolulope Adams',
  description: 'Generated by create next app',
  // openGraph: {
  //   title: 'Tolulope Adams',
  //   description: 'Generated by create next app',
  //   url: 'https://tolulopeadams.com',
  //   siteName: 'Tolulope Adams',
  //   images: [
  //     {
  //       url: '/og-image.png',
  //       width: 1200,
  //       height: 630,
  //       alt: 'Tolulope Adams',
  //     },
  //   ],
  //   locale: 'en_US',
  //   type: 'website',
  // },
}



import { ThemeProvider } from '@/components/ThemeProvider'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
        <link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet" type='text/css' />
        <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" type='text/css' />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}


